### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\snapshot\node\tmp\pkg\cli\node_modules\rfc4648\lib\cjs\rfc4648.js require() of ES modules is not supported.

### ISSUE THREAD

**Issue by JitendraBhoyar** [swansontec/rfc4648.js#33] opened 2023-11-13 11:24 UTC
Hi i am using kubernetes/client-node (0.14.3) dependency in my project which internally uses rfc4648 version 1.3.0. Suddenly i have started getting following error while it was working fine for couple of weeks before. Can somebody please help me or guide me on this?
I am kind of stuck and not able to proceed further.
Error - 
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\snapshot\node\tmp\pkg\cli\node_modules\rfc4648\lib\cjs\rfc4648.js
require() of ES modules is not supported.
require() of C:\snapshot\node\tmp\pkg\cli\node_modules\rfc4648\lib\cjs\rfc4648.js from C:\snapshot\node\tmp\pkg\cli\node_modules\@kubernetes\client-node\dist\oidc_auth.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename rfc4648.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\snapshot\node\tmp\pkg\cli\node_modules\rfc4648\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1152:13)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1338:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\snapshot\node\tmp\pkg\cli\node_modules\@kubernetes\client-node\dist\oidc_auth.js:6:19)

```

**Comment by swansontec** [comment] 2023-11-14 20:54
I recently released rfc4648 v1.5.3 to address a packaging issue: https://github.com/storybookjs/storybook/issues/22542

Based on the timeline, it sounds like this release may have broken your project instead. If we can verify that the previous release still works for you (rfc4648 v1.5.2), I can take a look at what may have caused this.

**Comment by JitendraBhoyar** [comment] 2023-11-15 07:15
Thanks for the response @swansontec , but i am using rfc4648 version 1.3.0. Do you think it will still conflict with this? And the repo it resolves this dependency from is https://registry.yarnpkg.com/rfc4648/.
Does it internally still resolves to 1.5.3? most unlikely though.
I tried changing the version in yarn.lock as 1.0.0 also, still was facing same issue.
Please suggest.

**Comment by JitendraBhoyar** [comment] 2023-11-17 08:57
Can i please get any help on this one ...tried different versions but still getting same. kind of stuck from long.

**Comment by JitendraBhoyar** [comment] 2023-11-21 14:11
when i check this, it gives
$ yarn why rfc4648
yarn why v1.22.5
[1/4] Why do we have the module "rfc4648"...?
[2/4] Initialising dependency graph...
warning Lockfile has incorrect entry for "rfc4648@^1.3.0". Ignoring it.
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "**rfc4648@1.5.3**"
info Reasons this module exists
   - "_project_#@garden-io#core#@kubernetes#client-node" depends on it
   - Hoisted from "_project_#@garden-io#core#@kubernetes#client-node#rfc4648"
Done in 2.86s.


not sure why it picks up latest version of rfc4648 although its specified as 1.3.0

**Comment by swansontec** [comment] 2023-11-22 21:32
Oh, the `^` in `^1.3.0` means "any compatible higher version", so just delete the `^`, and now Yarn will be forced to install the exact version.

**Comment by swansontec** [comment] 2023-11-22 21:48
As for the bug itself, Node.js seems to believe that the file `C:\snapshot\node\tmp\pkg\cli\node_modules\rfc4648\lib\cjs\rfc4648.js` is an ES6 module. However, the file `C:\snapshot\node\tmp\pkg\cli\node_modules\rfc4648\lib\cjs\package.json` should be present on disk, and should contain the text `{"type":"commonjs"}`. This is supposed to tell Node.js that the file is *not* an ES6 module, but rather a CommonJS module.

Here is the mystery: why isn't Node.js reading this inner package.json file?

- Is the file even present on disk?
- Does it contain the right text?
- Is this even running on Node.js, or maybe some other runtime?
- Is there something else weird going on, like Yarn PnP?

I cannot reproduce the issue on this end - the inner package.json file is indeed present, and it successfully switches Node.js into the right mode.

**Comment by JitendraBhoyar** [comment] 2023-11-23 07:32
I tried with specific version also i.e. 1.3.0 but still it gives me same error. I dont see lib/cjs/package.json though.
![image](https://github.com/swansontec/rfc4648.js/assets/142817580/ea817448-8d57-41d8-a724-7ab9e99459de)

![image](https://github.com/swansontec/rfc4648.js/assets/142817580/dfabd24b-117b-497a-b52b-e734012a4421)

**Comment by swansontec** [comment] 2023-12-01 18:51
If the file `/lib/cjs/package.json` is present, then everything should work fine, and the error should be impossible! I am running out of ideas.

Unless there are somehow multiple copies of rfc4648 present in your node_modules folder, and we are looking at the wrong one.

**Comment by swansontec** [comment] 2024-02-02 18:11
I will close this issue, since there are no updates. If somebody can provide additional details, I will happily re-open this and get it fixed.

**Closed as completed by swansontec** 2024-02-02 18:11 UTC
